project: BALL-TRAJECTORY_CONV1D_BAYES_clean
name: BALL-TRAJECTORY_CONV1D_BAYES_clean
method: bayes
metric:
  goal: maximize
  name: val_accuracy
parameters:
  epochs:
    values: [1000]
  patience:
    values: [100]
  first_half_only:
    values: [False, True]
  angles_only:
    values: [False]
  trajectories_only:
    values: [False]
  use_distance:
    values: [True, False]
  use_padding:
    values: [True, False]
  label_type:
    values: [clean]
  test_size:
    values: [0.25, 0.1]
  batch_size:
    values: [32, 16, 4]
  activation_function:
    values: [leakyrelu, relu, prelu]
  optimizer:
    values: [SGD, Adam, AdamW]
  learning_rate:
    max: 0.001
    min: 0.00001
  scheduler:
    values: [ReduceLROnPlateau, CosineAnnealingLR]
  hidden_size:
    values: [512, 256, 128, 2048]
  kernel_sizes:
    values: [[1, 1], [1, 3], [2, 3], [3, 5], [1, 2], [2, 1]]
  conv_neurons:
    values: [[256, 512], [512, 256], [512, 1024], [1024, 512]]
  skip_connection:
    values: [True, False]
  dropout:
    values: [0.5, 0.25, 0.1]
